const {test}=require('node:test');
const assert=require('node:assert/strict');
test('native history waits for IME completion without replaying stale requests',async()=>{
  const {observeComposition,routeHistory}=await import('../web/edit-history.js');
  const events=new EventTarget();
  const document=Object.assign(events,{activeElement:{tagName:'TEXTAREA',getAttribute:()=> '문서 편집 입력'},querySelector:()=>null});
  const calls=[];
  const editor={commands:{execute:async a=>calls.push(a)}};
  observeComposition(document);observeComposition(document);
  events.dispatchEvent(new Event('compositionstart'));
  await routeHistory('undo',{document,editor});
  await routeHistory('redo',{document,editor});
  assert.deepEqual(calls,[]);
  events.dispatchEvent(new Event('compositionend'));
  assert.deepEqual(calls,[]);
  await routeHistory('undo',{document,editor});
  assert.deepEqual(calls,['edit:undo']);
});
test('history routes document input to engine and dialog fields to their own history',async()=>{
  const {routeHistory}=await import('../web/edit-history.js');
  const calls=[];
  const inner={activeElement:{tagName:'TEXTAREA',getAttribute:()=> '문서 편집 입력'},querySelector:()=>null,execCommand:a=>calls.push('field:'+a)};
  const document={activeElement:{tagName:'IFRAME',contentDocument:inner},querySelector:()=>null};
  const editor={commands:{execute:async a=>calls.push(a)}};
  await routeHistory('undo',{document,editor});
  await routeHistory('redo',{document,editor});
  assert.deepEqual(calls,['edit:undo','edit:redo']);
  inner.activeElement={tagName:'INPUT',getAttribute:()=>null};
  await routeHistory('undo',{document,editor});
  assert.equal(calls.at(-1),'field:undo');
  inner.activeElement={tagName:'DIV',isContentEditable:true,getAttribute:()=>null};
  await routeHistory('redo',{document,editor});
  assert.equal(calls.at(-1),'field:redo');
  inner.activeElement={tagName:'BUTTON'};
  inner.querySelector=()=>({});
  await routeHistory('undo',{document,editor});
  inner.querySelector=()=>null;
  await routeHistory('undo',{document,editor,busy:true});
  await routeHistory('paste',{document,editor});
  await routeHistory('undo',{document});
  assert.equal(calls.length,4);
});
